name: CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Docker Hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Build Go application
        run: |
          go mod tidy
          go build -C cmd/valkyrie-db/ -o ../../bin/valkyrie-db

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/valkyrie:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/valkyrie:latest
